CarRental/src/CarRental.Web/Controllers/Web/AutoController.cs
using CarRental.DataAccess.Entities;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Mvc;
using System.IO;
using System.Web.UI;

namespace CarRental.Web.Controllers.Web
{
    public class AutoController : Controller
    {
        private IHostingEnvironment _environment;


        public AutoController(IHostingEnvironment environment)
        {
            _environment = environment;
        }

        [Authorize(Roles = UserStatus.Admin + "," + UserStatus.Master + "," + UserStatus.SuperAdmin)]
        public IActionResult AutoIndex()
        {
            ViewData["Title"] = "Automobiliai";
            return View();
        }

        public IActionResult AutoCreate()
        {
            ViewData["Title"] = "Naujas automobilis";
            return View();
        }

        public IActionResult AutoDelete(int id)
        {
            ViewData["Title"] = "Automobilio pašalinimas";
            ViewBag.autoId = id;
            return View();
        }

        public IActionResult AutoDetails(int id)
        {
            ViewData["Title"] = "Automobilis detaliau";
            ViewBag.autoId = id;
            ViewBag.adress = "/Uploads/";
            return View();
        }

        public IActionResult AutoEdit(int id)
        {
            ViewData["Title"] = "Automobilio redagavimas";
            ViewBag.autoId = id;
            ViewBag.adress = "/Uploads/";
            return View();
        }
    }
}

CarRental/src/CarRental.Web/Views/Shared/_Layout.cshtml
@using CarRental.DataAccess.Entities;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRental</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/bootstrap-datetimepicker.min.css" rel="stylesheet" /> 
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>   
    <script src="~/js/moment.js"></script>
    <script src="https://raw.githubusercontent.com/Eonasdan/bootstrap-datetimepicker/master/build/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/site.js"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">CarRental</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(UserStatus.Admin) ||User.IsInRole(UserStatus.Master) || User.IsInRole(UserStatus.SuperAdmin))
                    {
                        <li><a asp-controller="Order" asp-action="OrderIndex">Užsakymai</a></li>
                        <li><a asp-controller="Auto" asp-action="AutoIndex">Automobiliai</a></li>
                    }
                    @if (User.IsInRole(UserStatus.Master) || User.IsInRole(UserStatus.SuperAdmin))
                    {
                        <li><a asp-controller="Account" asp-action="Master">Vartotojai</a></li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="AccountSettings">Profilis</a></li>
                        <li><a asp-controller="Account" asp-action="Logout">Atsijungti</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Register">Registracija</a></li>
                        <li><a asp-controller="Account" asp-action="Login">Prisijungti</a></li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CarRental</p>
        </footer>
    </div>

    

    <environment names="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        @*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bundle.js" asp-append-version="true"></script>

        
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

   


    @*@RenderSection("scripts", required: false)*@
</body>
</html>